import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

sender_email = "gateman56@gmail.com"
password = "lekzjeuykwytooxj"
receiver_email = "jason1.pan@hsbc.com.hk"

msg = MIMEMultipart()
msg['From'] = sender_email
msg['To'] = receiver_email
msg['Subject'] = "Jira Epic Breakdown: Data migration from CDR to RCDP (RRIS)"

body = """
Hi Jason,

Here is the Jira story breakdown for the RRIS migration from CDR to RCDP, formatted as requested:

### Epic: Data migration from CDR to RCDP : RRIS

#### Part 1: Data Gap Analysis & Remediation

**Story 1.1**
**Subject:** [Analysis] Assess Historical Data & Schema Gap for RRIS MI
**Description:**
*   **Background:** RRIS MI team relies on CDR for historical data and specific tables/fields. We need to identify if RCDP currently has all the required data before they can migrate off CDR.
*   **As a** RCDP Data Engineer
*   **I want to** collaborate with the RRIS MI team to compare the existing RRIS data in RCDP against their current usage in CDR
*   **So that** we can identify any missing historical data ranges or missing tables/fields (Data Gap) and decide the remediation approach.
**Acceptance Criteria:**
1.  A gap analysis report is documented on Confluence detailing missing historical data periods.
2.  A schema gap report is documented detailing missing tables and fields required by RRIS MI.
3.  A decision is made and documented on whether to fetch missing data directly from the RRIS source or migrate it from the legacy CDR database.

**Story 1.2**
**Subject:** [Data Eng] Remediate RRIS Historical Data Gap
**Description:**
*   **Background:** The gap analysis (Story 1.1) identified missing RRIS historical data in RCDP that is required by the downstream MI team.
*   **As a** RCDP Data Engineer
*   **I want to** ingest or migrate the identified missing historical data into RCDP
*   **So that** the RCDP raw layer has the complete historical dataset equivalent to what is currently available in CDR.
**Acceptance Criteria:**
1.  One-off ingestion jobs or migration scripts are developed and executed successfully.
2.  Data reconciliation (row counts/checksums) between the source (RRIS/CDR) and RCDP target tables matches.

**Story 1.3**
**Subject:** [Data Eng] Enhance Pipeline for Missing RRIS Tables & Fields
**Description:**
*   **Background:** The gap analysis (Story 1.1) identified that certain RRIS tables and fields required by MI are not currently ingested into RCDP's daily batch/stream.
*   **As a** RCDP Data Engineer
*   **I want to** enhance the RCDP ingestion pipeline to capture the missing RRIS tables and fields
*   **So that** RCDP receives all necessary daily delta data moving forward.
**Acceptance Criteria:**
1.  Ingestion pipelines (e.g., Dataflow) are updated to include the new tables/fields.
2.  Data successfully lands in the RCDP raw layer.
3.  Daily scheduling is configured and verified.

#### Part 2: Downstream Integration & Presentation Layer

**Story 2.1**
**Subject:** [Infra] Setup Connectivity & IAM for RRIS MI
**Description:**
*   **Background:** The RRIS MI team needs infrastructure access to query RCDP (BigQuery) to replace their legacy CDR connection.
*   **As a** RCDP Infra/Security Admin
*   **I want to** provision Service Accounts and grant appropriate BigQuery IAM roles to the RRIS MI team
*   **So that** they have the necessary connectivity and permissions to access RCDP data securely.
**Acceptance Criteria:**
1.  Dedicated Service Account(s) are created for RRIS MI.
2.  Appropriate IAM roles (e.g., BigQuery Data Viewer) are granted to the authorized datasets.
3.  Connectivity is successfully tested and confirmed by the RRIS MI team.

**Story 2.2**
**Subject:** [Data Eng] Build Presentation Layer Views for RRIS MI
**Description:**
*   **Background:** RRIS MI consumes data from CDR using specific translation logic, joins, and derivations. We need to replicate this in RCDP to minimize disruption for the downstream team.
*   **As a** RCDP Data Engineer
*   **I want to** build Authorized/Presentation Views in BigQuery that encapsulate the legacy CDR translation logic
*   **So that** the RRIS MI team can query RCDP using a structure and logic as close to their existing CDR setup as possible.
**Acceptance Criteria:**
1.  Legacy CDR SQL/Logic is reviewed with the CDR and MI teams.
2.  BigQuery SQL views are created in the presentation dataset.
3.  The output structure of the views matches the agreed-upon MI requirements.

**Story 2.3**
**Subject:** [Testing] End-to-End Testing & Parallel Run with RRIS MI
**Description:**
*   **Background:** Before cutting over to production, we must ensure the data generated by RCDP exactly matches or safely replaces what CDR currently provides.
*   **As a** RCDP Tech Lead / QA
*   **I want to** support the RRIS MI team in executing end-to-end tests and parallel runs
*   **So that** we can verify data accuracy, performance, and obtain UAT sign-off for production cutover.
**Acceptance Criteria:**
1.  RRIS MI successfully connects their reporting tools to RCDP presentation views.
2.  Parallel run results (CDR reports vs RCDP reports) are compared and any discrepancies are resolved or accepted.
3.  Formal UAT sign-off is provided by the RRIS MI business/tech owners.

#### Part 3: Decommission & Disconnect

**Story 3.1**
**Subject:** [Cutover] Disconnect RRIS and RRIS MI from Legacy CDR
**Description:**
*   **Background:** RCDP is now successfully serving RRIS MI data in production. The legacy pipelines must be shut down to achieve the final demise goal.
*   **As a** RCDP Tech Lead
*   **I want to** coordinate with the RRIS and CDR teams to disable legacy data feeds and MI extracts
*   **So that** CDR is completely decoupled from the RRIS data flow, completing the demise objective.
**Acceptance Criteria:**
1.  RRIS upstream stops sending data feeds to CDR.
2.  RRIS MI downstream stops fetching data from CDR.
3.  Legacy CDR ingestion and extraction jobs for RRIS are formally disabled/decommissioned.

Best regards,
Alice (OpenClaw)
"""

msg.attach(MIMEText(body, 'plain'))

try:
    server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
    server.login(sender_email, password)
    text = msg.as_string()
    server.sendmail(sender_email, receiver_email, text)
    server.quit()
    print("Email sent successfully")
except Exception as e:
    print(f"Failed to send email: {e}")
